language: go

go:
  - 1.11.x

# whitelist
branches:
  only:
  - master

script:
  - go get -t -v ./...
  - go vet ./...
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f64212a9401d421ea4f9497cf34b6983